# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TLM.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(942, 818)
        MainWindow.setMinimumSize(QtCore.QSize(942, 818))
        MainWindow.setMaximumSize(QtCore.QSize(942, 818))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textCookie = QtWidgets.QTextEdit(self.centralwidget)
        self.textCookie.setGeometry(QtCore.QRect(10, 30, 771, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.textCookie.setFont(font)
        self.textCookie.setObjectName("textCookie")
        self.textURL = QtWidgets.QTextEdit(self.centralwidget)
        self.textURL.setGeometry(QtCore.QRect(10, 100, 771, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.textURL.setFont(font)
        self.textURL.setObjectName("textURL")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 81, 31))
        self.label.setObjectName("label")
        self.btnWeibo = QtWidgets.QPushButton(self.centralwidget)
        self.btnWeibo.setGeometry(QtCore.QRect(860, 30, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnWeibo.sizePolicy().hasHeightForWidth())
        self.btnWeibo.setSizePolicy(sizePolicy)
        self.btnWeibo.setObjectName("btnWeibo")
        self.btnUpload = QtWidgets.QPushButton(self.centralwidget)
        self.btnUpload.setGeometry(QtCore.QRect(790, 30, 61, 101))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUpload.sizePolicy().hasHeightForWidth())
        self.btnUpload.setSizePolicy(sizePolicy)
        self.btnUpload.setObjectName("btnUpload")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 71, 31))
        self.label_2.setObjectName("label_2")
        self.btnUploadPic = QtWidgets.QPushButton(self.centralwidget)
        self.btnUploadPic.setGeometry(QtCore.QRect(10, 140, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnUploadPic.sizePolicy().hasHeightForWidth())
        self.btnUploadPic.setSizePolicy(sizePolicy)
        self.btnUploadPic.setObjectName("btnUploadPic")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 270, 71, 71))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.textPlayed = QtWidgets.QTextEdit(self.centralwidget)
        self.textPlayed.setGeometry(QtCore.QRect(840, 430, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.textPlayed.setFont(font)
        self.textPlayed.setObjectName("textPlayed")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(280, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(790, 430, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(790, 520, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(790, 610, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(790, 700, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(430, 750, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.textProgramAiming = QtWidgets.QTextEdit(self.centralwidget)
        self.textProgramAiming.setGeometry(QtCore.QRect(280, 230, 641, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textProgramAiming.sizePolicy().hasHeightForWidth())
        self.textProgramAiming.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.textProgramAiming.setFont(font)
        self.textProgramAiming.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textProgramAiming.setObjectName("textProgramAiming")
        self.tbSpread = QtWidgets.QTextBrowser(self.centralwidget)
        self.tbSpread.setGeometry(QtCore.QRect(840, 520, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbSpread.setFont(font)
        self.tbSpread.setObjectName("tbSpread")
        self.tbTopic = QtWidgets.QTextBrowser(self.centralwidget)
        self.tbTopic.setGeometry(QtCore.QRect(840, 610, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbTopic.setFont(font)
        self.tbTopic.setObjectName("tbTopic")
        self.tbLiked = QtWidgets.QTextBrowser(self.centralwidget)
        self.tbLiked.setGeometry(QtCore.QRect(840, 700, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tbLiked.setFont(font)
        self.tbLiked.setObjectName("tbLiked")
        self.tbGeneralScore = QtWidgets.QTextBrowser(self.centralwidget)
        self.tbGeneralScore.setGeometry(QtCore.QRect(550, 750, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.tbGeneralScore.setFont(font)
        self.tbGeneralScore.setObjectName("tbGeneralScore")
        self.btnBzhan = QtWidgets.QPushButton(self.centralwidget)
        self.btnBzhan.setGeometry(QtCore.QRect(860, 90, 71, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnBzhan.sizePolicy().hasHeightForWidth())
        self.btnBzhan.setSizePolicy(sizePolicy)
        self.btnBzhan.setObjectName("btnBzhan")
        self.textPeriod = QtWidgets.QTextEdit(self.centralwidget)
        self.textPeriod.setGeometry(QtCore.QRect(280, 340, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.textPeriod.setFont(font)
        self.textPeriod.setObjectName("textPeriod")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 400, 381, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 400, 381, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lblPic = QtWidgets.QLabel(self.centralwidget)
        self.lblPic.setGeometry(QtCore.QRect(10, 170, 241, 221))
        self.lblPic.setFrameShape(QtWidgets.QFrame.Box)
        self.lblPic.setText("")
        self.lblPic.setObjectName("lblPic")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionDLM = QtWidgets.QAction(MainWindow)
        self.actionDLM.setObjectName("actionDLM")
        self.actionLLLMDDG = QtWidgets.QAction(MainWindow)
        self.actionLLLMDDG.setObjectName("actionLLLMDDG")
        self.actionss = QtWidgets.QAction(MainWindow)
        self.actionss.setObjectName("actionss")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TLMGDX"))
        self.label.setText(_translate("MainWindow", "输入Cookie："))
        self.btnWeibo.setText(_translate("MainWindow", "爬微博"))
        self.btnUpload.setText(_translate("MainWindow", "上传"))
        self.label_2.setText(_translate("MainWindow", "输入URL："))
        self.btnUploadPic.setText(_translate("MainWindow", "选择图片"))
        self.label_4.setText(_translate("MainWindow", "期数："))
        self.label_6.setText(_translate("MainWindow", "栏目定位："))
        self.label_8.setText(_translate("MainWindow", "播放量："))
        self.label_9.setText(_translate("MainWindow", "传播率："))
        self.label_10.setText(_translate("MainWindow", "话题性："))
        self.label_11.setText(_translate("MainWindow", "点赞率："))
        self.label_12.setText(_translate("MainWindow", "综合质量评分："))
        self.btnBzhan.setText(_translate("MainWindow", "爬B站"))
        self.groupBox.setTitle(_translate("MainWindow", "话题分布情况："))
        self.groupBox_2.setTitle(_translate("MainWindow", "情感倾向："))
        self.actionDLM.setText(_translate("MainWindow", "DLM"))
        self.actionLLLMDDG.setText(_translate("MainWindow", "LLLMDDG"))
        self.actionss.setText(_translate("MainWindow", "ss"))
